### ISSUE TITLE
ci commit change type check failed

### ISSUE THREAD

**Issue by WAMiii** [godfather1103/commit-template-check-plugin#21]
**Describe the bug**
Commit message is "ci(cache):  xxxxxxxx", then check failed which errors is `length should be no less than 3`.

**To Reproduce**
1. Commit Message is   "ci(cache):  xxxxxxxx"
2. check failed

**Expected behavior**
Check passed.

**Screenshots**
![image](https://github.com/godfather1103/commit-template-check-plugin/assets/49750324/5fcc6286-bcbf-41ee-8ede-6ca7b2a30b83)

![image](https://github.com/godfather1103/commit-template-check-plugin/assets/49750324/a3ef4c7c-5b99-4fda-9926-acffe82b28c6)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by godfather1103** [comment]
plugin version？

**Comment by WAMiii** [comment]
> plugin version？

1.8.6

Version 1.8.8 is available.

**Comment by WAMiii** [comment]
> > plugin version？
> 
> 1.8.6

Version 1.8.8 is available
